package io.jenkins.plugins.constants;

public class ResultValues {
    public static final String DUDE_STATISTICS_HTML_PATH = "/dude-statistics.html";
    public static final String DUDE_STATISTICS_JSON_PATH = "/dude-statistics.json";

    // For table 1 with overall analysis
    public static final String VALUE_NOT_AVAILABLE = "N/A";
    public static final String PROJECT_NAME = "$PROJECT_NAME$";
    public static final String CURRENT_BUILD_NUMBER = "$CURRENT_BUILD_NUMBER$";
    public static final String PREVIOUS_BUILD_NUMBER = "$PREVIOUS_BUILD_NUMBER$";
    public static final String NUMBER_OF_FILES_ANALYSED = "$NUMBER_OF_FILES_ANALYSED$";
    public static final String NUMBER_OF_DUPLICATED_CODE_FRAGMENTS = "$NUMBER_OF_DUPLICATED_CODE_FRAGMENTS$";
    public static final String NUMBER_OF_FILES_CONTAINING_DUPLICATE_FRAGMENTS = "$NUMBER_OF_FILES_CONTAINING_DUPLICATE_FRAGMENTS$";
    public static final String FILES_WITH_DUPLICATE_FRAGMENTS = "$FILES_WITH_DUPLICATE_FRAGMENTS$";
    public static final String PERCENTAGE_OF_FILES_ANALYSED_THAT_HAVE_DUPLICATE_FRAGMENTS =
            "$PERCENTAGE_OF_FILES_ANALYSED_THAT_HAVE_DUPLICATE_FRAGMENTS$";
    public static final String PREVIOUS_PERCENTAGE_OF_FILES_ANALYSED_THAT_HAVE_DUPLICATE_FRAGMENTS =
            "$PREVIOUS_PERCENTAGE_OF_FILES_ANALYSED_THAT_HAVE_DUPLICATE_FRAGMENTS$";

    // For table 2 with DuplicationFragment analysis
    public static final String DUPLICATION_FRAGMENT_WITH_MOST_LOC_TOTAL_LOC = "$DUPLICATION_FRAGMENT_WITH_MOST_LOC_TOTAL_LOC$";
    public static final String DUPLICATION_FRAGMENT_WITH_MOST_LOC_ACTUAL_LOC = "$DUPLICATION_FRAGMENT_WITH_MOST_LOC_ACTUAL_LOC$";
    public static final String DUPLICATION_FRAGMENT_WITH_MOST_LOC_FILES_COUNT =
            "$DUPLICATION_FRAGMENT_WITH_MOST_LOC_FILES_COUNT$";
    public static final String DUPLICATION_FRAGMENT_WITH_MOST_LOC_FILES = "$DUPLICATION_FRAGMENT_WITH_MOST_LOC_FILES$";

    public static final String DUPLICATION_FRAGMENT_PRESENT_IN_MOST_FILES_TOTAL_LOC =
            "$DUPLICATION_FRAGMENT_PRESENT_IN_MOST_FILES_TOTAL_LOC$";
    public static final String DUPLICATION_FRAGMENT_PRESENT_IN_MOST_FILES_ACTUAL_LOC =
            "$DUPLICATION_FRAGMENT_PRESENT_IN_MOST_FILES_ACTUAL_LOC$";
    public static final String DUPLICATION_FRAGMENT_PRESENT_IN_MOST_FILES_FILES_COUNT =
            "$DUPLICATION_FRAGMENT_PRESENT_IN_MOST_FILES_FILES_COUNT$";
    public static final String DUPLICATION_FRAGMENT_PRESENT_IN_MOST_FILES_FILES =
            "$DUPLICATION_FRAGMENT_PRESENT_IN_MOST_FILES_FILES$";

    // For table 3 with trend analysis
    public static final String DUPLICATION_TREND = "$DUPLICATION_TREND$";
    public static final String DUPLICATION_IMPACT = "$DUPLICATION_IMPACT$";
}
